site_name: ConstructCloud server
site_url: https://ConstructCloud.github.io/server
repo_url: https://github.com/ConstructCloud/server
edit_uri: edit/master/docs/

theme:
  name: material

docs_dir: ../docs

nav:
  - Home: index.md
  - Setup: setup.md
  - Usage: usage.md
  - Workflows: workflows.md
  - Contributing: contributing.md
  - Documentation: documentation.md
