name: ci

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: make setup

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build
        run: make build
