name: mkdocs

on:
  push:
    branches: [master]
    paths:
      - "docs/**"
      - ".github/mkdocs.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install MkDocs
        run: pip install mkdocs mkdocs-material

      - name: Build site
        run: mkdocs build -f .github/mkdocs.yml --strict

      - name: Configure Pages
        uses: actions/configure-pages@v5
        with:
          token: ${{ secrets.PAGES_TOKEN }}
          enablement: true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .github/site
      - id: deployment
        uses: actions/deploy-pages@v4
